### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer.github.io#28]
For syntax highlighting, jekyll already parses the code and wraps tokens in spans with different CSS classes. All we need is some CSS to set the colors, e.g.

```css
pre.highlight .k { /* keyword */
    color: #0b65ca;
}
```
